Ec2 spot managed nodegroups
raghananth/eks-workshop pull request #1
Opened 2021-03-19 16:25 UTC by raghananth

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-26 12:06 UTC, ruecarlo requested changes

2021-03-26 12:06 UTC, ruecarlo commented on content/beginner/150_spotnodegroups/_index.md
> +![Spot Node Groups Architecture](/images/spotworkers/spot_nodegroup_arch.png)
Really cosmetic one, I wouldn't stop pushing for this, but here is an idea:  Perhaps we should have a way to differentiate in the image the fact that the Spot node groups are (well actually all of them !) are managed nodegroups. I think we should add some kind of reference at those being part of the EKS API's system rather than something that K8s offers (managed nodegroups)

2021-03-26 12:06 UTC, ruecarlo commented on content/beginner/150_spotnodegroups/spotnodegroups.md
> +We have our EKS Cluster and nodes already, but we need some Spot Instances configured to run the workload. We will be creating managed nodegroup to utilize Spot Instances. We also need a Node Labelin
Why the capitals in "Node Labeling" ?  also change Labeling for "Labelling"

2021-03-26 12:06 UTC, ruecarlo commented on content/beginner/150_spotnodegroups/spotnodegroups.md
> +But first, we will add a new label to the On-Demand nodes
I may suggest changing for : 

```
But first, given that all the current nodes are On-Demand, we will add a that label to the nodes.
```

2021-03-26 12:06 UTC, ruecarlo commented on content/beginner/150_spotnodegroups/spotnodegroups.md
> +eksctl create nodegroup --cluster=eksworkshop-eksctl --region=${AWS_REGION} --managed --spot --name=ng-spot --instance-types=m5.large,m4.large,m5d.large,m5a.large,m5ad.large,m5n.large,m5dn.large --no
A few points on this.

First one in instance selection.M5dn are not that common and probably not available across regions. You can leave this as an example, but we should add something like
```
{{% notice warning %}}
Note, the instances above might not be present in your region. To select instances that meet that criteria in your region, you could install [https://github.com/aws/amazon-ec2-instance-selector`](https://github.com/aws/amazon-ec2-instance-selector) and execute the command `ec2-instance-selector --base-instance-type m5.large --flexible` to get a diversified selection of instances available in your region of choice that meet the criteria of being similar to m4.large (in vCPU and memory terms)
{{% /notice %}}
```

Also, there are quite a lot of entries in the long line command... perhaps it might be better to use this following format, so attributes are easier to read and digest. 

```
eksctl create nodegroup \
  --cluster=eksworkshop-eksctl --region=${AWS_REGION} \
  --managed --spot --name=ng-spot \
  --instance-types=m5.large,m4.large,m5d.large,m5a.large,m5ad.large,m5n.large,m5dn.large \
  --node-labels="lifecycle=Ec2Spot"
```

And regarding this point: we should keep an eye on  is this https://github.com/weaveworks/eksctl/pull/3476 pull request in EKSCTL.  I reckon once this PR comes out and we have eksctl updated in the workshop we should amend this section to use that functionality and simplify the selection and implement spot diversification best practices in even a simpler way.

2021-03-26 12:06 UTC, ruecarlo commented on content/beginner/150_spotnodegroups/spotnodegroups.md
> +The node groups created follows Spot best practices including using [capacity-optimized](https://aws.amazon.com/blogs/compute/introducing-the-capacity-optimized-allocation-strategy-for-amazon-ec2-spo
I'd suggest removing the parenthesis in the lines. 

```
(out of the instance types we specified)
```

```
(when EC2 needs the capacity back)
```

Both of the entries are well justified to be in the sentence

2021-03-26 12:06 UTC, ruecarlo commented on content/beginner/150_spotnodegroups/spotnodegroups.md
> +![All Nodes](/images/spotworkers/spot_get_nodes.png)
All the image points to 1.14... that's (5 majors versions behind), Spot Manage node groups were not even supported on that version !!! This makes the workshop are not up to date even if they are.  I'd suggest for the images to be updated accordingly.

2021-03-26 12:06 UTC, ruecarlo commented on content/beginner/150_spotnodegroups/spotlifecycle.md
> +Demand for Spot Instances can vary significantly, and as a consequence the availability of Spot Instances will also vary depending on how many unused EC2 instances are available. It is always possibl
The first part in that paragraph is a bit vague, ambiguous. Also the last sentence in that paragraph only made sense when we were deploying the node termination handler as a daemonset, which is not the case with Managed node groups.

How about changing it for something like the following:


> Spot instances are unused EC2 instances that might be reclaimed when OnDemand users require capacity from a specific capacity pool. A Spot capacity pool is a set of unused EC2 instances with the same instance type (for example, m5.large) and Availability Zone. It is possible that your Spot Instance might be interrupted. In this case the Spot Instances are sent an interruption notice two minutes ahead to gracefully wrap up things. EKS Spot Managed node groups re-provision capacity from other available spot pools and redeploy the application elsewhere in the cluster.

2021-03-26 12:06 UTC, ruecarlo commented on content/beginner/150_spotnodegroups/spotnodegroups.md
> +![Spot Output](/images/spotworkers/spot_get_spot.png)
Same for the update of this image

2021-03-26 12:06 UTC, ruecarlo commented on content/beginner/150_spotnodegroups/spotlifecycle.md
> +Spot Managed node groups automatically deploys the [AWS Node Termination Handler](https://github.com/aws/aws-node-termination-handler) on each Spot Instance. This will monitor the EC2 metadata servic
I think this does not cover how Spot managed node group works... we should change this page. Some examples on this:

`This will monitor the EC2 metadata service on the instance for an interruption notice.`. 

This is not the case with Spot managed node groups, this is the node termination handler behaviour when running as a daemonset using the "IMDS". But this is not the way it works for Spot Managed node groups. 

Second thing, the content below is really confusing and should be simplified. There should be just one diagram, the one used for the reinvent session.

In this PR the document explains both notifications individually, first interruption and then rebalancing recommendation. The reality is that there is only one single sequence of events. By default the Spot Managed nodegroup is configured with this ASG setup

![image](https://user-images.githubusercontent.com/46894578/112625543-fed1dd00-8e26-11eb-9aa4-f3d190a4b825.png)

Given that the Spot Managed node group node termination handler is configured to use rebalancing recommendations, it means that the actual sequence of events (in most cases) will be the one depicted below. 

![image](https://user-images.githubusercontent.com/46894578/112626242-dc8c8f00-8e27-11eb-90e4-c8349d0c04e5.png)

This is closer to the second diagram in your document except that... The wrong notifications are used, for example instead of "T0 Instance receives Instance termination", it should say refer to a "system receives a Rebalancing notification" and instead of the green arrow having the "Rebalance Recommendation" name on it use "Rebalancing activity in progress". ....  I could mention a few more, but I'd refer just to use the same messaging as the one that was created for reInvent instead.

2021-03-26 12:06 UTC, ruecarlo commented on content/beginner/150_spotnodegroups/deployapp.md
> +date: 2021-03-08T10:00:00-08:00
👍  For the extra yml files in the deployment solutions for all the changes... Good contribution to help customers validate the code and get the final solution if that's what they want !

2021-03-26 19:06 UTC, raghananth commented on content/beginner/150_spotnodegroups/_index.md
> +![Spot Node Groups Architecture](/images/spotworkers/spot_nodegroup_arch.png)
Will utilize the diagram from https://aws.amazon.com/blogs/containers/eks-managed-node-groups/ here to showcase the managed node groups.

2021-03-29 15:31 UTC, ruecarlo approved these changes

2021-03-31 13:56 UTC, closed without merging